# Generated by Django 5.0.1 on 2024-03-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnails',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/product_images/thumbnails/'),
        ),
    ]
