# Generated by Django 5.0.7 on 2024-07-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in-transit', 'in-transit'), ('delivered', 'Delivered')], default='pending', max_length=50),
        ),
    ]
